### ISSUE TITLE
Add info for [octopath traveler champions of the continent] (English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#242] opened 2022-08-04 08:59 UTC
- **Game:** octopath traveler champions of the continent
- **Server region/language:** English
- **Server timezone (location or offset):** ???
- **Server daily reset time:** ???
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-09-10 09:43
Duplicate of #241

**Closed by cicerakes** 2022-09-10 09:43 UTC
Labels: game request, created via form
