### ISSUE TITLE
Add info for [NIKKE: GODDESS OF VICTORY ] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#280] opened 2022-11-08 03:34 UTC
- **Game:** NIKKE: GODDESS OF VICTORY 
- **Server region/language:** Global
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 12 am
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-06 15:44
Duplicate of #288

**Closed by cicerakes** 2022-12-06 15:44 UTC
Labels: game request, created via form
