### ISSUE TITLE
Add info for [Snowbreak: Containment Zone] (Southeast Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#408] opened 2023-08-16 14:07 UTC
- **Game:** Snowbreak: Containment Zone
- **Server region/language:** Southeast Asia
- **Server timezone (location or offset):** idk
- **Server daily reset time:** idk
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-09-10 15:07
Duplicate of #391

**Closed by cicerakes** 2023-09-10 15:07 UTC
Labels: duplicate, game request, created via form
