### ISSUE TITLE
Add info for [Project SEKAI COLORFUL STAGE! feat. Hatsune Miku] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#425] opened 2023-10-19 12:53 UTC
- **Game:** Project SEKAI COLORFUL STAGE! feat. Hatsune Miku
- **Server region/language:** EN
- **Server timezone (location or offset):** PST
- **Server daily reset time:** 4am PST
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2023-10-29 12:45
Duplicate of #157

**Closed by cicerakes** 2023-10-29 12:45 UTC
Labels: game request, created via form
