### ISSUE TITLE
[Fate/Grand Order] (JP) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#181] opened 2022-02-27 19:15 UTC
- **Game:** Fate/Grand Order
- **Server region/language:** JP

**Correct information:** 
- **Timezone (location or offset):** Already correct
- **Server daily reset time:**  Time Until Reset:  0 hours 10 minutes 5 seconds at Your local time: 03:10:28  Monday, 28th February, 2022  Asia/Shanghai — GMT +08:00

(Optional) Provide an explanation and/or links/screenshots as proof: 
https://imgur.com/a/f3cRhUI

The time seems off and for some reason the timer is increasing instead of decreasing

**Comment by cicerakes** [comment] 2022-03-04 08:33
Duplicate of #50

Refreshing the page should fix the problem.

**Closed by cicerakes** 2022-03-04 08:33 UTC
Labels: duplicate, created via form
