### ISSUE TITLE
Add info for [Alchemia Story] (Japan, English global server)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#152] opened 2021-12-09 07:50 UTC
- **Game:** Alchemia Story
- **Server region/language:** Japan, English global server
- **Server timezone (location or offset):** JST
- **Server daily reset time:** dunno orz
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2021-12-30 09:48
Duplicate of #158

**Closed by cicerakes** 2021-12-30 09:48 UTC
Labels: duplicate, game request, created via form
