### ISSUE TITLE
Add info for [Afk Journey] (NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#495] opened 2024-04-10 23:23 UTC
- **Game:** Afk Journey
- **Server region/language:** NA
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 0:00 UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:59
Duplicate of #490

**Closed by cicerakes** 2024-12-08 13:59 UTC
Labels: duplicate, game request, created via form
