### ISSUE TITLE
Add info for [Outerplane] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#411] opened 2023-09-02 00:03 UTC
- **Game:** Outerplane
- **Server region/language:** Global
- **Server timezone (location or offset):** US & Canada Central Standard Time
- **Server daily reset time:** 7 pm
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-09-10 14:46
Duplicate of #377

**Closed by cicerakes** 2023-09-10 14:46 UTC
Labels: game request, created via form
