### ISSUE TITLE
Add info for [Eversoul] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#332] opened 2023-02-28 03:22 UTC
- **Game:** Eversoul
- **Server region/language:** Asia
- **Server timezone (location or offset):** GMT+7
- **Server daily reset time:** 07:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 14:48
Duplicate of #314

**Closed by cicerakes** 2023-04-25 14:48 UTC
Labels: duplicate, game request, created via form
