### ISSUE TITLE
[goddess of victory nikke] (global) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#396] opened 2023-07-30 23:18 UTC
- **Game:** goddess of victory nikke
- **Server region/language:** global

**Correct information:** 
- **Timezone (location or offset):** Already correct
- **Server daily reset time:** Already correct

(Optional) Provide an explanation and/or links/screenshots as proof: 
the time until next reset counter is broken seems fine when approaching the time but then it starts counting back up instead of resetting to 23h59 example here:  https://imgur.com/a/z7oZftT

**Comment by cicerakes** [comment] 2023-09-10 14:36
Duplicate of #50

**Closed by cicerakes** 2023-09-10 14:36 UTC
Labels: game data correction, created via form
