### ISSUE TITLE
Add info for [AFK Journey] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#553] opened 2024-09-04 20:15 UTC
- **Game:** AFK Journey
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 00:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2024-12-08 13:59
Duplicate of #490

**Closed by cicerakes** 2024-12-08 13:59 UTC
Labels: duplicate, game request, created via form
