### ISSUE TITLE
Fate/Grand Order (JP) has incorrect data

### ISSUE THREAD

**Issue by LamSauced** [cicerakes/Game-Time-Master#244] opened 2022-08-05 22:55 UTC
- **Game:** Fate/Grand Order
- **Server region/language:** JP

**Correct information:** 
- **Timezone (location or offset):** -
- **Server daily reset time:** -

(Optional) Provide an explanation and/or links/screenshots as proof.
The timezone and reset time seem correct but the timer that shows when the server resets is incorrect. Instead of resetting the timer and counting down again to the server reset time, the timer starts at zero and just starts counting up.
![image](https://user-images.githubusercontent.com/90363825/183221275-95d4ad02-86fa-449e-a92e-e467e11f8505.png)

**Comment by cicerakes** [comment] 2022-09-10 08:52
This is a known issue, and refreshing the page should fix it.

Duplicate of #50

**Closed by cicerakes** 2022-09-10 08:52 UTC
Labels: game data correction
