### ISSUE TITLE
Add info for [Limbus Company] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#342] opened 2023-03-30 03:57 UTC
- **Game:** Limbus Company
- **Server region/language:** Global/English
- **Server timezone (location or offset):** KST
- **Server daily reset time:** 4AM GMT +7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 15:05
Duplicate of #345

**Closed by cicerakes** 2023-04-25 15:05 UTC
Labels: duplicate, game request, created via form
