### ISSUE TITLE
Add info for [Neural Cloud] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#300] opened 2022-11-26 13:06 UTC
- **Game:** Neural Cloud
- **Server region/language:** Global
- **Server timezone (location or offset):** GMT+7
- **Server daily reset time:** 11.00PM (GMT+7)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-07 06:28
Duplicate of #299

**Closed by cicerakes** 2022-12-07 06:28 UTC
Labels: game request, created via form
