### ISSUE TITLE
Add info for [Hatsune Miku: Colorful Stage] (Global version )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#191] opened 2022-03-21 03:19 UTC
- **Game:** Hatsune Miku: Colorful Stage
- **Server region/language:** Global version 
- **Server timezone (location or offset):** PHT
- **Server daily reset time:** PHT
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-04-23 05:44
Duplicate of #157

**Closed by cicerakes** 2022-04-23 05:44 UTC
Labels: duplicate, game request, created via form
