### ISSUE TITLE
Add info for [Aether Gazer] (America - EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#380] opened 2023-06-04 05:35 UTC
- **Game:** Aether Gazer
- **Server region/language:** America - EN
- **Server timezone (location or offset):** No idea, probably UTC
- **Server daily reset time:** 9AM on GMT-3 (Brazil TZ)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:54
Duplicate of #368

**Closed by cicerakes** 2023-06-04 13:54 UTC
Labels: duplicate, game request, created via form
