### ISSUE TITLE
Add info for [Aether Gazer] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#371] opened 2023-05-25 12:28 UTC
- **Game:** Aether Gazer
- **Server region/language:** Global
- **Server timezone (location or offset):** GMT -7
- **Server daily reset time:** 5AM GMT -7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:53
Duplicate of #368

**Closed by cicerakes** 2023-06-04 13:53 UTC
Labels: duplicate, game request, created via form
