### ISSUE TITLE
Add info for [Girls' Frontline: Project Neural Cloud] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#297] opened 2022-11-23 20:57 UTC
- **Game:** Girls' Frontline: Project Neural Cloud
- **Server region/language:** EN
- **Server timezone (location or offset):** We think it's UTC -8
- **Server daily reset time:** 7 A.M. CST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-07 06:37
Duplicate of #299

**Closed by cicerakes** 2022-12-07 06:37 UTC
Labels: game request, created via form
