### ISSUE TITLE
Add info for [BrownDust 2] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#424] opened 2023-10-13 17:32 UTC
- **Game:** BrownDust 2
- **Server region/language:** Global/English
- **Server timezone (location or offset):** GMT-5
- **Server daily reset time:** 3:00pm
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:31
Duplicate of #486

**Closed by cicerakes** 2024-12-08 13:31 UTC
Labels: duplicate, game request, created via form
