### ISSUE TITLE
Add info for [The eminence in shadow RPG] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#333] opened 2023-02-28 10:03 UTC
- **Game:** The eminence in shadow RPG
- **Server region/language:** Global
- **Server timezone (location or offset):** Sorry I don't remember
- **Server daily reset time:** 19:00 UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 15:38
Duplicate of #304

**Closed by cicerakes** 2023-04-25 15:38 UTC
Labels: duplicate, game request, created via form
