### ISSUE TITLE
Add info for [World dai star: yume no stellarium] (Japan server)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#496] opened 2024-04-13 14:12 UTC
- **Game:** World dai star: yume no stellarium
- **Server region/language:** Japan server
- **Server timezone (location or offset):** Tokyo, Japan (i think)
- **Server daily reset time:** 5:00 am I believe
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 05:51
Duplicate of #409

**Closed by cicerakes** 2024-12-08 05:50 UTC
Labels: duplicate, game request, created via form
