### ISSUE TITLE
Add info for [Goddess of Victory: Nikke] (North America)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#364] opened 2023-05-10 23:45 UTC
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** North America
- **Server timezone (location or offset):** UNSURE
- **Server daily reset time:** 6am UTC+10
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:52
Duplicate of #301

**Closed by cicerakes** 2023-06-04 13:52 UTC
Labels: duplicate, game request, created via form
