### ISSUE TITLE
Add info for [life makeover] (global/english)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#427] opened 2023-10-23 02:59 UTC
- **Game:** life makeover
- **Server region/language:** global/english
- **Server timezone (location or offset):** unknown/unsure
- **Server daily reset time:** unknown/unsure
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-10-29 13:16
Duplicate of #365

**Closed by cicerakes** 2023-10-29 13:16 UTC
Labels: duplicate, game request, created via form

**Comment by cicerakes** [comment] 2023-10-29 14:08
Added in 3c4281265c97f0784e278294a5ad43615192e9e2
