### ISSUE TITLE
Add info for [afk journey  ] (america)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#514] opened 2024-05-27 01:54 UTC
- **Game:** afk journey  
- **Server region/language:** america
- **Server timezone (location or offset):** est
- **Server daily reset time:** 7 pm est
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment] 2024-12-08 13:59
Duplicate of #490

**Closed by cicerakes** 2024-12-08 13:59 UTC
Labels: duplicate, game request, created via form
