### ISSUE TITLE
Add info for [Girl's Frontline 2] (Global/EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#602] opened 2024-12-07 07:21 UTC
- **Game:** Girl's Frontline 2
- **Server region/language:** Global/EN
- **Server timezone (location or offset):** -
- **Server daily reset time:** 11:18 PM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 03:32
Duplicate of #591

**Closed by cicerakes** 2024-12-08 03:32 UTC
Labels: game request, created via form
