### ISSUE TITLE
Add info for [Reverse 1999] (Global/NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#432] opened 2023-10-27 17:13 UTC
- **Game:** Reverse 1999
- **Server region/language:** Global/NA
- **Server timezone (location or offset):** UTC-5
- **Server daily reset time:** 12:00 UTC-0
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-10-29 12:48
Duplicate of #435

**Closed by cicerakes** 2023-10-29 12:48 UTC
Labels: game request, created via form
