### ISSUE TITLE
Add info for [Sword of convallaria] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#555] opened 2024-09-04 23:53 UTC
- **Game:** Sword of convallaria
- **Server region/language:** Global
- **Server timezone (location or offset):** -
- **Server daily reset time:** I don't get quite the precise time but it's around 11:00 to 13:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:46
Duplicate of #551

**Closed by cicerakes** 2024-12-08 13:46 UTC
Labels: duplicate, game request, created via form
