### ISSUE TITLE
Add info for [Aether Gazer] (Global / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#374] opened 2023-05-29 10:15 UTC
- **Game:** Aether Gazer
- **Server region/language:** Global / English
- **Server timezone (location or offset):** UTC - 7
- **Server daily reset time:** 8PM PHT (UTC +8)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:54
Duplicate of #368

**Closed by cicerakes** 2023-06-04 13:54 UTC
Labels: duplicate, game request, created via form
