### ISSUE TITLE
Add info for [Eversoul] (USA/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#318] opened 2023-01-19 00:10 UTC
- **Game:** Eversoul
- **Server region/language:** USA/English
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** Central Time United States
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 14:48
Duplicate of #314

**Closed by cicerakes** 2023-04-25 14:48 UTC
Labels: game request, created via form
