### ISSUE TITLE
Add info for [Goddess of Victory: Nikke] (Global )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#281] opened 2022-11-08 18:17 UTC
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** Global 
- **Server timezone (location or offset):** GMT
- **Server daily reset time:** Unsure
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment] 2022-12-06 15:46
Duplicate of #288

**Closed by cicerakes** 2022-12-06 15:46 UTC
Labels: game request, created via form
