### ISSUE TITLE
Add info for [Ni no Kuni: Cross Worlds] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#208] opened 2022-05-28 16:56 UTC
- **Game:** Ni no Kuni: Cross Worlds
- **Server region/language:** Global
- **Server timezone (location or offset):** NA
- **Server daily reset time:** NA
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-05-30 16:20
You did not provide a daily reset time, and I am unable to find it through research.

**Comment by cicerakes** [comment] 2022-06-08 04:49
Duplicate of #217

**Closed by cicerakes** 2022-06-08 04:49 UTC
Labels: duplicate, game request, created via form
