### ISSUE TITLE
Add info for [aether gazer] (global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#369] opened 2023-05-24 21:36 UTC
- **Game:** aether gazer
- **Server region/language:** global
- **Server timezone (location or offset):** UTC-7
- **Server daily reset time:** 5 AM
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2023-06-04 13:53
Duplicate of #368

**Closed by cicerakes** 2023-06-04 13:53 UTC
Labels: game request, created via form
