### ISSUE TITLE
Add info for [Girl's Frontline 2 Exilium] (Global, Sunborn)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#600] opened 2024-12-07 07:13 UTC
- **Game:** Girl's Frontline 2 Exilium
- **Server region/language:** Global, Sunborn
- **Server timezone (location or offset):** UTC-4
- **Server daily reset time:** 5:00 AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment] 2024-12-08 03:33
Duplicate of #591

**Closed by cicerakes** 2024-12-08 03:33 UTC
Labels: game request, created via form
