### ISSUE TITLE
Add info for [Goddess of Victory: Nikke] (NA)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#292] opened 2022-11-19 09:20 UTC
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** NA
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 20:00 UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-06 15:45
Duplicate of #301

**Closed by cicerakes** 2022-12-06 15:45 UTC
Labels: game request, created via form
