### ISSUE TITLE
Add info for [Path to Nowhere] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#274] opened 2022-10-31 09:45 UTC
- **Game:** Path to Nowhere
- **Server region/language:** EN
- **Server timezone (location or offset):** UTC+2
- **Server daily reset time:** 05:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-06 14:57
Duplicate of #275

**Closed by cicerakes** 2022-12-06 14:57 UTC
Labels: game request, created via form
