### ISSUE TITLE
[Goddess of Victory: Nikke] (NA) has incorrect data

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#322] opened 2023-01-28 23:53 UTC
- **Game:** Goddess of Victory: Nikke
- **Server region/language:** NA

**Correct information:** 
- **Timezone (location or offset):** Already correct
- **Server daily reset time:** Already correct

(Optional) Provide an explanation and/or links/screenshots as proof: 
It is counting UP from reset not counting down To reset

**Comment by cicerakes** [comment] 2023-04-25 14:14
Duplicate of #50

**Closed by cicerakes** 2023-04-25 14:14 UTC
Labels: bug, duplicate, created via form
