### ISSUE TITLE
Add info for [Project SEKAI Colorful Stage] (English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#176] opened 2022-02-12 08:07 UTC
- **Game:** Project SEKAI Colorful Stage
- **Server region/language:** English
- **Server timezone (location or offset):** PST
- **Server daily reset time:** 12AM PST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-03-04 08:51
This has already been added, the English version is named `HATSUNE MIKU: COLORFUL STAGE!`.

Duplicate of #157.

**Closed by cicerakes** 2022-03-04 08:51 UTC
Labels: game request, created via form
