### ISSUE TITLE
Add info for [Destiny 2] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#376] opened 2023-05-30 17:00 UTC
- **Game:** Destiny 2
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC+5
- **Server daily reset time:** 5pm UTC+5
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:59
Duplicate of #326

**Closed by cicerakes** 2023-06-04 13:59 UTC
Labels: duplicate, game request, created via form
