### ISSUE TITLE
Add info for [Aether Gazer] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#379] opened 2023-06-03 05:34 UTC
- **Game:** Aether Gazer
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC-9
- **Server daily reset time:** 8:00 AM UTC-5
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:54
Duplicate of #368

**Closed by cicerakes** 2023-06-04 13:54 UTC
Labels: game request, created via form
