### ISSUE TITLE
Add info for [Nikke: Goddess of Victory] (Global / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#308] opened 2022-12-07 14:40 UTC
- **Game:** Nikke: Goddess of Victory
- **Server region/language:** Global / English
- **Server timezone (location or offset):** UTC+9
- **Server daily reset time:** 3PM EST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-07 15:09
This game has already been added.

Duplicate of #288

**Closed by cicerakes** 2022-12-07 15:09 UTC
Labels: game request, created via form
