### ISSUE TITLE
Add info for [OuterPlane] (GLOBAL/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#407] opened 2023-08-14 01:42 UTC
- **Game:** OuterPlane
- **Server region/language:** GLOBAL/English
- **Server timezone (location or offset):** I don't know I missed it
- **Server daily reset time:** I don't know I missed it
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-09-10 14:46
Duplicate of #377

**Closed by cicerakes** 2023-09-10 14:46 UTC
Labels: game request, created via form
