### ISSUE TITLE
Add info for [Outerplane] (Asia / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#375] opened 2023-05-29 11:18 UTC
- **Game:** Outerplane
- **Server region/language:** Asia / English
- **Server timezone (location or offset):** UTC 
- **Server daily reset time:** 8AM PHT (UTC + 8)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-09-10 14:47
Duplicate of #377

**Closed by cicerakes** 2023-09-10 14:47 UTC
Labels: duplicate, game request, created via form
