### ISSUE TITLE
Add info for [Shall We Date?: Obey Me!] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#258] opened 2022-09-05 00:30 UTC
- **Game:** Shall We Date?: Obey Me!
- **Server region/language:** Global/English
- **Server timezone (location or offset):** JST
- **Server daily reset time:** 00:00 (JST)/23:00 (GMT+8)
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-09-10 09:59
Duplicate of #255

**Closed by cicerakes** 2022-09-10 09:59 UTC
Labels: game request, created via form
