### ISSUE TITLE
Add info for [Sword of Convallaria] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#598] opened 2024-12-07 07:06 UTC
- **Game:** Sword of Convallaria
- **Server region/language:** Global
- **Server timezone (location or offset):** Canada, Vancouver 
- **Server daily reset time:** 8:00 PM
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment] 2024-12-08 13:46
Duplicate of #551

**Closed by cicerakes** 2024-12-08 13:46 UTC
Labels: duplicate, game request, created via form
