### ISSUE TITLE
Add info for [Lord of Heros] (North America/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#247] opened 2022-08-13 02:29 UTC
- **Game:** Lord of Heros
- **Server region/language:** North America/English
- **Server timezone (location or offset):** EST, New York
- **Server daily reset time:** 12 AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-09-10 10:08
Duplicate of #86.

[See here](https://github.com/cicerakes/Game-Time-Master/issues/86#issuecomment-880441762) for reasons why this won't be added.

**Closed by cicerakes** 2022-09-10 10:08 UTC
Labels: game request, created via form
