### ISSUE TITLE
Add info for [eversoul] (na)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#329] opened 2023-02-21 02:19 UTC
- **Game:** eversoul
- **Server region/language:** na
- **Server timezone (location or offset):** est
- **Server daily reset time:** 7pm
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 14:48
Duplicate of #314

**Closed by cicerakes** 2023-04-25 14:48 UTC
Labels: duplicate, game request, created via form
