### ISSUE TITLE
Add info for [Girls' frontline project neural cloud] (GLOBAL/EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#303] opened 2022-12-04 12:04 UTC
- **Game:** Girls' frontline project neural cloud
- **Server region/language:** GLOBAL/EN
- **Server timezone (location or offset):** GMT +8
- **Server daily reset time:** 21:00 PHST
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2022-12-07 06:28
Duplicate of #299

**Closed by cicerakes** 2022-12-07 06:28 UTC
Labels: game request, created via form
