### ISSUE TITLE
Add info for [Sword of Convallaria] (Global, Taiwan)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#562] opened 2024-10-22 17:31 UTC
- **Game:** Sword of Convallaria
- **Server region/language:** Global, Taiwan
- **Server timezone (location or offset):** Unsure
- **Server daily reset time:** 9:30 AM Indian Standard Time
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:46
Duplicate of #551

**Closed by cicerakes** 2024-12-08 13:46 UTC
Labels: duplicate, game request, created via form
