### ISSUE TITLE
Add info for [Echocalypse] (SEA/Indonesia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#260] opened 2022-09-09 20:09 UTC
- **Game:** Echocalypse
- **Server region/language:** SEA/Indonesia
- **Server timezone (location or offset):** UTC+7
- **Server daily reset time:** UTC+7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-09-10 10:49
Please provide a **server daily reset time** and not just an offset (e.g. 9AM), as I could not find info for it.

**Comment by cicerakes** [comment] 2022-10-24 14:26
Duplicate of #270

**Closed by cicerakes** 2022-10-24 14:26 UTC
Labels: question, game request, created via form
