### ISSUE TITLE
Add info for [Eversoul] (Korean)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#321] opened 2023-01-25 20:50 UTC
- **Game:** Eversoul
- **Server region/language:** Korean
- **Server timezone (location or offset):** Korea
- **Server daily reset time:** 7pm
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 14:48
Duplicate of #314

**Closed by cicerakes** 2023-04-25 14:48 UTC
Labels: duplicate, game request, created via form
