### ISSUE TITLE
Add info for [Mythic Heroes] (Global / English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#164] opened 2022-01-18 23:50 UTC
- **Game:** Mythic Heroes
- **Server region/language:** Global / English
- **Server timezone (location or offset):** UTC 0
- **Server daily reset time:** UTC 0
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-01-22 13:08
Duplicate of #162

**Closed by cicerakes** 2022-01-22 13:08 UTC
Labels: duplicate, game request, created via form
