### ISSUE TITLE
Add info for [Limbus Company] (EN/Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#331] opened 2023-02-27 19:23 UTC
- **Game:** Limbus Company
- **Server region/language:** EN/Global
- **Server timezone (location or offset):** Korea, UTC+9
- **Server daily reset time:** 11:00 PM UTC +3
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 15:05
Duplicate of #345

**Closed by cicerakes** 2023-04-25 15:05 UTC
Labels: duplicate, game request, created via form
