### ISSUE TITLE
Add info for [Neural Cloud] (EN)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#296] opened 2022-11-22 14:00 UTC
- **Game:** Neural Cloud
- **Server region/language:** EN
- **Server timezone (location or offset):** can't find it sorry
- **Server daily reset time:** 19:00 GMT+7
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-07 06:28
Duplicate of #299

**Closed by cicerakes** 2022-12-07 06:28 UTC
Labels: game request, created via form
