### ISSUE TITLE
Add info for [Path to Nowhere] (Europe)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#285] opened 2022-11-11 15:01 UTC
- **Game:** Path to Nowhere
- **Server region/language:** Europe
- **Server timezone (location or offset):** UTC+0
- **Server daily reset time:** 03:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-06 15:00
Duplicate of #275

**Closed by cicerakes** 2022-12-06 15:00 UTC
Labels: game request, created via form
