### ISSUE TITLE
Add info for [Figure Fantasy] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#184] opened 2022-03-04 12:57 UTC
- **Game:** Figure Fantasy
- **Server region/language:** Global
- **Server timezone (location or offset):** GMT+7
- **Server daily reset time:** 17
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2022-03-04 14:01
Duplicate of #170 and #172.

**Closed by cicerakes** 2022-03-04 14:01 UTC
Labels: game request, created via form
