### ISSUE TITLE
Add info for [Dislyte] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#207] opened 2022-05-25 09:04 UTC
- **Game:** Dislyte
- **Server region/language:** Global/English
- **Server timezone (location or offset):** Not sure
- **Server daily reset time:** Not sure
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-05-30 15:53
Duplicate of #204

**Closed by cicerakes** 2022-05-30 15:53 UTC
Labels: game request, created via form
