### ISSUE TITLE
Add info for [NU: Carnival] (EN )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#233] opened 2022-07-07 04:55 UTC
- **Game:** NU: Carnival
- **Server region/language:** EN 
- **Server timezone (location or offset):** unsure
- **Server daily reset time:** GMT+8, 5:00 AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-07-19 07:03
Duplicate of #196

**Closed by cicerakes** 2022-07-19 07:03 UTC
Labels: game request, created via form
