### ISSUE TITLE
Add info for [Girls Frontline: Neural Cloud-EN] (Global/Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#306] opened 2022-12-06 10:09 UTC
- **Game:** Girls Frontline: Neural Cloud-EN
- **Server region/language:** Global/Asia
- **Server timezone (location or offset):** UTC+08:00, Singapore
- **Server daily reset time:** 20:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-07 06:28
Duplicate of #299

**Closed by cicerakes** 2022-12-07 06:28 UTC
Labels: game request, created via form
