### ISSUE TITLE
Add info for [Punishing Grey Raven] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#165] opened 2022-01-19 00:45 UTC
- **Game:** Punishing Grey Raven
- **Server region/language:** Asia
- **Server timezone (location or offset):** UTC+8
- **Server daily reset time:** 10:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Yes

**Comment by cicerakes** [comment] 2022-01-22 13:37
Asia has already been added, as `China and Taiwan` region.

Duplicate of #61

**Closed by cicerakes** 2022-01-22 13:37 UTC
Labels: duplicate, game request, created via form
