### ISSUE TITLE
Add info for [Destiny 2] (Global - English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#381] opened 2023-06-04 05:38 UTC
- **Game:** Destiny 2
- **Server region/language:** Global - English
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 5pm UTC
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-06-04 13:59
Duplicate of #326

**Closed by cicerakes** 2023-06-04 13:59 UTC
Labels: duplicate, game request, created via form
