### ISSUE TITLE
Add info for [Dislyte] (America/ English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#210] opened 2022-05-29 22:44 UTC
- **Game:** Dislyte
- **Server region/language:** America/ English
- **Server timezone (location or offset):** (UTC+0) 
- **Server daily reset time:** 00:00
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-05-30 15:53
Duplicate of #204

**Closed by cicerakes** 2022-05-30 15:53 UTC
Labels: game request, created via form
