### ISSUE TITLE
Add info for [Punishing gray raven] (Asia Pacific/english)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#290] opened 2022-11-14 02:49 UTC
- **Game:** Punishing gray raven
- **Server region/language:** Asia Pacific/english
- **Server timezone (location or offset):** WIB
- **Server daily reset time:** Nothing
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2022-12-07 06:40
Duplicate of #200

**Closed by cicerakes** 2022-12-07 06:40 UTC
Labels: game request, created via form

**Comment by cicerakes** [comment] 2022-12-07 06:44
Asia-Pacific server goes under Global, which has already been added.
