### ISSUE TITLE
Add info for [counter side global] (en )

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#209] opened 2022-05-29 18:22 UTC
- **Game:** counter side global
- **Server region/language:** en 
- **Server timezone (location or offset):** idk
- **Server daily reset time:** idk
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-05-30 16:24
Duplicate of #62

**Closed by cicerakes** 2022-05-30 16:24 UTC
Labels: game request, created via form
