### ISSUE TITLE
Add info for [Honkai star Rail] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#353] opened 2023-04-24 20:23 UTC
- **Game:** Honkai star Rail
- **Server region/language:** Asia
- **Server timezone (location or offset):** UTC+08
- **Server daily reset time:** WIB
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-05-01 16:01
Duplicate of #357

**Closed by cicerakes** 2023-05-01 16:01 UTC
Labels: game request, created via form
