### ISSUE TITLE
Add info for [Snowbreak: Containment Zone] (All)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#386] opened 2023-07-27 14:48 UTC
- **Game:** Snowbreak: Containment Zone
- **Server region/language:** All
- **Server timezone (location or offset):** UTC+8
- **Server daily reset time:** 05:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2023-09-10 15:07
Duplicate of #391

**Closed by cicerakes** 2023-09-10 15:07 UTC
Labels: game request, created via form
