### ISSUE TITLE
Add info for [Final Fantasy VII: Ever Crisis] (Global/English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#556] opened 2024-09-12 16:37 UTC
- **Game:** Final Fantasy VII: Ever Crisis
- **Server region/language:** Global/English
- **Server timezone (location or offset):** GMT-4
- **Server daily reset time:** 04:00 PM GMT-4
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:23
Duplicate of #412

**Closed by cicerakes** 2024-12-08 13:23 UTC
Labels: duplicate, game request, created via form
