### ISSUE TITLE
Add info for [What in Hell is Bad] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#429] opened 2023-10-26 22:10 UTC
- **Game:** What in Hell is Bad
- **Server region/language:** Global
- **Server timezone (location or offset):** KST
- **Server daily reset time:** 11 PM GMT+8
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-10-29 12:57
Duplicate of #426

**Closed by cicerakes** 2023-10-29 12:57 UTC
Labels: duplicate, game request, created via form
