### ISSUE TITLE
Add info for [Reverse: 1999] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#434] opened 2023-10-28 15:50 UTC
- **Game:** Reverse: 1999
- **Server region/language:** Global
- **Server timezone (location or offset):** UTC-5
- **Server daily reset time:** Unsure
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-10-29 12:49
Duplicate of #435

**Closed by cicerakes** 2023-10-29 12:49 UTC
Labels: game request, created via form
