### ISSUE TITLE
Add info for [Eversoul] (NA/Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#320] opened 2023-01-24 02:01 UTC
- **Game:** Eversoul
- **Server region/language:** NA/Global
- **Server timezone (location or offset):** 00:00 UTC
- **Server daily reset time:** 7:00 pm EST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-04-25 14:48
Duplicate of #314

**Closed by cicerakes** 2023-04-25 14:48 UTC
Labels: duplicate, game request, created via form
