### ISSUE TITLE
Add info for [Honkai: Star Rail] (Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#363] opened 2023-05-05 20:06 UTC
- **Game:** Honkai: Star Rail
- **Server region/language:** Asia
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 03:00
- **(Optional) Does the server reset time change during the server's daylight savings?** No

**Comment by cicerakes** [comment] 2023-06-04 13:50
Duplicate of #357

**Closed by cicerakes** 2023-06-04 13:50 UTC
Labels: duplicate, game request, created via form
