### ISSUE TITLE
Add info for [afk journey] (AFK Journey)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#563] opened 2024-10-28 19:42 UTC
- **Game:** afk journey
- **Server region/language:** AFK Journey
- **Server timezone (location or offset):** UTC
- **Server daily reset time:** 08:00AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:59
Duplicate of #490

**Closed by cicerakes** 2024-12-08 13:59 UTC
Labels: duplicate, game request, created via form
