### ISSUE TITLE
Add info for [Goddess of Victory: Nikke ] (South East Asia)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#286] opened 2022-11-11 17:09 UTC
- **Game:** Goddess of Victory: Nikke 
- **Server region/language:** South East Asia
- **Server timezone (location or offset):** GMT +8
- **Server daily reset time:** 4:00 PHT 
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2022-12-06 15:22
Duplicate of #278

**Closed by cicerakes** 2022-12-06 15:22 UTC
Labels: game request, created via form
