### ISSUE TITLE
Add info for [Snowbreak: Containtment Zone] (Japan)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#398] opened 2023-08-08 15:29 UTC
- **Game:** Snowbreak: Containtment Zone
- **Server region/language:** Japan
- **Server timezone (location or offset):** GMT+8
- **Server daily reset time:** 8 or 9 pm BST
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2023-09-10 15:07
Duplicate of #391

**Closed by cicerakes** 2023-09-10 15:07 UTC
Labels: duplicate, game request, created via form
