### ISSUE TITLE
Add info for [Final Fantasy Vii Ever Crisis] (Global)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#528] opened 2024-06-10 08:47 UTC
- **Game:** Final Fantasy Vii Ever Crisis
- **Server region/language:** Global
- **Server timezone (location or offset):** jst
- **Server daily reset time:** 0600 jst
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by cicerakes** [comment] 2024-12-08 13:23
Duplicate of #412

**Closed by cicerakes** 2024-12-08 13:23 UTC
Labels: game request, created via form
